// constants.js
export const IDLE='IDLE';

export const BOOKINGS_STEP = {
    SEARCH_TRIPS:'SEARCH_TRIPS',
    SELECT_SEATS:'SELECT_SEATS',
    PAYING:'PAYING'
};

export const BOOKINGS_STATUS = {
    PENDING_CREATE_BOOKING:'PENDING_CREATE_BOOKING',
    PENDING_PAY_BOOKING:'PENDING_PAY_BOOKING'
};

export const ACCOUNT_STATUS = {
    PENDING_LOGIN:'PENDING_LOGIN',
    PENDING_RESGITER:'PENDING_RESGITER',
    PENDING_UPDATE_INFO:'PENDING_UPDATE_INFO'
};

export const STATE_OFFICE_STATUS={
    PENDING_FETCH_OFFICES:'PENDING_FETCH_OFFICES',
    PENDING_FETCH_TRIPDETAIL:'PENDING_FETCH_TRIPDETAIL',
}
