// constants.js
export const IDLE='IDLE';

export const BOOKINGS_STEP = {
    SEARCH_TRIPS:'SEARCH_TRIPS',
    SELECT_SEATS:'SELECT_SEATS',
    PAYING:'PAYING'
};

export const BOOKINGS_STATUS = {
    PENDING_CREATE_BOOKING:'PENDING_CREATE_BOOKING',
    PENDING_PAY_BOOKING:'PENDING_PAY_BOOKING',
    PENDING_FECTCH_BOOKINGS:'PENDING_FECTCH_BOOKINGS',
};

export const ACCOUNT_STATUS = {
    PENDING_LOGIN:'PENDING_LOGIN',
    PENDING_RESGITER:'PENDING_RESGITER',
    PENDING_UPDATE_INFO:'PENDING_UPDATE_INFO'
};

export const STATE_OFFICE_STATUS={
    PENDING_FETCH_OFFICES:'PENDING_FETCH_OFFICES',
    PENDING_FETCH_TRIPDETAIL:'PENDING_FETCH_TRIPDETAIL',
}

export const MANAGEMENT_STATUS={
    PENDING_FETCH_TOWNS:'PENDING_FETCH_TOWNS',

    PENDING_FETCH_OFFICES:'PENDING_FETCH_OFFICES',
    PENDING_CREATE_OFFICES:'PENDING_CREATE_OFFICES',
    PENDING_EDIT_OFFICES:'PENDING_EDIT_OFFICES',

    PENDING_FETCH_ROUTES:'PENDING_FETCH_ROUTES',
    PENDING_CREATE_ROUTES:'PENDING_CREATE_ROUTES',
    PENDING_EDIT_ROUTES:'PENDING_EDIT_ROUTES',

    PENDING_FETCH_TRIPS:'PENDING_FETCH_TRIPS',
    PENDING_CREATE_TRIP:'PENDING_CREATE_TRIP',
    PENDING_EDIT_TRIP:'PENDING_EDIT_TRIP',

    PENDING_FETCH_BOOKINGS:'PENDING_FETCH_BOOKINGS',
    PENDING_CREATE_BOOKING:'PENDING_CREATE_BOOKING',
    PENDING_EDIT_BOOKING:'PENDING_EDIT_BOOKING',
}
